#ifndef __GBIMERES_DEF_H__
#define __GBIMERES_DEF_H__

#ifdef __GBIME__
#include "MMI_features.h"
#include "MMIDataType.h"    /* for resource base */
#include "GlobalMenuItems.h"

/***************************************************************************** 
 * Typedef for Resource Enum
 *****************************************************************************/
/* Menu IDs */
typedef enum
{
    MENU_MAIN_GBIME = GBIME_BASE,

    /* add new menu ID above this line */
    MENU_ID_GBIME_END
} MENU_ID_GBIME_ENUM;

/* Screen IDs */
typedef enum
{
    SCR_MAIN_GBIME = GBIME_BASE,
    /* add new string ID below this line */
	SCR_ID_GUOBI_SETTING,
	SCR_ID_GUOBI_CHN_FUZZY_SETTING,
	SCR_ID_GUOBI_ALP_SETTING,
	SCR_ID_GUOBI_PRODUCT_CONFIGURATION, 
	SCR_ID_GUOBI_KEYBOARD_SETTING,
    /* add new screen ID above this line */
    SCR_ID_GBIME_END
} SCR_ID_GBIME_ENUM;

/* String IDs */
typedef enum
{
    STR_MAIN_GBIME = GBIME_BASE,
    /* add new string ID below this line */

	//主菜单ID
	STR_ID_GUOBI_SETTING,						//国笔输入法设置
	STR_ID_GUOBI_CHN_SETTING,					//中文输入法设置
	STR_ID_GUOBI_ALP_SETTING,					//英文输入法设置
	STR_ID_GUOBI_COMMON_SETTING,					//基本设置
	STR_ID_GUOBI_HANDWRITING_SETTING,				//手写设置
	STR_ID_GUOBI_HIDE_IME,						//隐藏输入法
	STR_ID_GUOBI_HELP,						//帮助
	STR_ID_GUOBI_ABOUT,						//关于

	//子菜单ID
	STR_ID_GUOBI_CHN_FUZZY_SETTING,				//中文模糊音设置
	STR_ID_GUOBI_DEFAULT_INPUT_KEYBOARD,		// 默认输入键盘
	STR_ID_GUOBI_DEFAULT_INPUT_MODE,			//默认输入模式
	STR_ID_GUOBI_SKIN_SELECT,					//皮肤选择
	STR_ID_GUOBI_PRODUCT_CONFIGURATION,			//产品配置
	STR_ID_GUOBI_HELP_FEATURES,				//帮助：一功能特点
	STR_ID_GUOBI_HELP_SELECT_INPUTMODE,			//帮助：二输入模式的选择
	STR_ID_GUOBI_HELP_SWITCHING_AND_HIDDEN_KEYBOARD,	//帮助：三键盘的切换和隐藏
	STR_ID_GUOBI_HELP_SMART_PINYIN_INPUT,			//帮助：四智能拼音的输入
	STR_ID_GUOBI_HELP_SMART_STROKE_INPUT,			//帮助：五智能笔画的输入
	STR_ID_GUOBI_HELP_SMART_ENG_INPUT,			//帮助：六智能英文的输入
	STR_ID_GUOBI_HELP_SYMBOL_INPUT,				//帮助：七符号输入
	STR_ID_GUOBI_HELP_HANDWRITING_INPUT,			//帮助：八手写输入
	STR_ID_GUOBI_HELP_SETTING,				//帮助：九设置
	
	STR_ID_GUOBI_HANDWRITING_TYPE,			//手写笔迹类型
	STR_ID_GUOBI_HANDWRITING_COLOR,			//手写笔迹颜色
	STR_ID_GUOBI_HANDWRITING_WIDTH,			//手写笔迹宽度
	STR_ID_GUOBI_HANDWRITING_SPOT_SPEED,	//手写识别速度	
	
	//选项ID
	STR_ID_GUOBI_CHN_FUZZY_H_F,
	STR_ID_GUOBI_CHN_FUZZY_K_G,
	STR_ID_GUOBI_CHN_FUZZY_N_L,	
	STR_ID_GUOBI_CHN_FUZZY_R_L,
	STR_ID_GUOBI_CHN_FUZZY_EN_ENG,
	STR_ID_GUOBI_CHN_FUZZY_Z_ZH,
	
	STR_ID_GUOBI_CHN_OPEN_STROKE_RADICAL,		//开启笔画部首功能

	STR_ID_GUOBI_ALP_AUTO_ADD_BLANKSPACE,		//自动添加空格
	STR_ID_GUOBI_ALP_AUTO_CORRECTION,			//英文智能纠错功能
	STR_ID_GUOBI_ALP_OPEN_ASSOC,				//开启英文联想功能

	STR_ID_GUOBI_KEYBOARD_NUMPAD,				// 数字键盘
	STR_ID_GUOBI_KEYBOARD_QWERTY,				// QWERTY键盘
	
	STR_ID_GUOBI_IM_SMART_PINYIN,				//智能拼音
	STR_ID_GUOBI_IM_SMART_STROKE,				//智能笔画
	STR_ID_GUOBI_IM_SMART_ENG,					//智能英文
	STR_ID_GUOBI_IM_SMART_HANDWRITING,			//国笔智能手写
	STR_ID_GUOBI_IM_SMART_SYMBOLS,				//国笔智能符号
				
	STR_ID_GUOBI_HW_TYPE_PEN,				//手写笔迹类型：钢笔
	STR_ID_GUOBI_HW_TYPE_PENCIL,			//手写笔迹类型：铅笔
	STR_ID_GUOBI_HW_TYPE_SYSTEM,			//手写笔迹类型：系统
	STR_ID_GUOBI_HW_COLOR_RED,				//手写笔迹颜色：红
	STR_ID_GUOBI_HW_COLOR_GREEN,			//手写笔迹颜色：绿
	STR_ID_GUOBI_HW_COLOR_BLUE,				//手写笔迹颜色：蓝
	STR_ID_GUOBI_HW_COLOR_YELLOW,			//手写笔迹颜色：黄
	STR_ID_GUOBI_HW_COLOR_PURPLE,			//手写笔迹颜色：紫
	STR_ID_GUOBI_HW_COLOR_GRAY,				//手写笔迹颜色：灰
	STR_ID_GUOBI_HW_COLOR_BLACK,				//手写笔迹颜色：黑
	STR_ID_GUOBI_HW_WIDTH_LARGE,			//手写笔迹宽度：大
	STR_ID_GUOBI_HW_WIDTH_MEDIUM,			//手写笔迹宽度：中
	STR_ID_GUOBI_HW_WIDTH_SMALL,			//手写笔迹宽度：小
	STR_ID_GUOBI_HW_SPEED_SLOW,				//手写识别速度：慢
	STR_ID_GUOBI_HW_SPEED_MEDIUM,			//手写识别速度：中
	STR_ID_GUOBI_HW_SPEED_FAST,				//手写识别速度：快
 
    /* add new screen ID above this line */
    STR_ID_GBIME_END
} STR_ID_GBIME_ENUM;

/* Image IDs */
typedef enum
{
    IMG_GBIME_SYSTEM = GBIME_BASE,
    /* add new image ID below this line */
	
/*V5 layout 图片*/
	IMG_GB_V5_0001,
	IMG_GB_V5_0002,
	IMG_GB_V5_0003,
	IMG_GB_V5_0004,
	IMG_GB_V5_0005,
	IMG_GB_V5_0006,
	IMG_GB_V5_0007,
	IMG_GB_V5_0008,
	IMG_GB_V5_0009,
	IMG_GB_V5_0010,
	IMG_GB_V5_0011,
	IMG_GB_V5_0012,
	IMG_GB_V5_0013,
	IMG_GB_V5_0014,
	IMG_GB_V5_0015,
	IMG_GB_V5_0016,
	IMG_GB_V5_0017,
	IMG_GB_V5_0018,
	IMG_GB_V5_0019,
	IMG_GB_V5_0020,
	IMG_GB_V5_0021,
	IMG_GB_V5_0022,
	IMG_GB_V5_0023,
	IMG_GB_V5_0024,
	IMG_GB_V5_0025,
	IMG_GB_V5_0026,
	IMG_GB_V5_0027,
	IMG_GB_V5_0028,
	IMG_GB_V5_0029,
	IMG_GB_V5_0030,
	IMG_GB_V5_0031,
	IMG_GB_V5_0032,
	IMG_GB_V5_0033,
	IMG_GB_V5_0034,
	IMG_GB_V5_0035,
	IMG_GB_V5_0036,
	IMG_GB_V5_0037,
	IMG_GB_V5_0038,
	IMG_GB_V5_0039,
	IMG_GB_V5_0040,
	IMG_GB_V5_0041,
	IMG_GB_V5_0042,
	IMG_GB_V5_0043,
	IMG_GB_V5_0044,
	IMG_GB_V5_0045,
	IMG_GB_V5_0046,
	IMG_GB_V5_0047,
	IMG_GB_V5_0048,
	IMG_GB_V5_0049,
	IMG_GB_V5_0050,
	IMG_GB_V5_0051,
	IMG_GB_V5_0052,
	IMG_GB_V5_0053,
	IMG_GB_V5_0054,
	IMG_GB_V5_0055,
	IMG_GB_V5_0056,
	IMG_GB_V5_0057,
	IMG_GB_V5_0058,
	IMG_GB_V5_0059,
	IMG_GB_V5_0060,
	IMG_GB_V5_0061,
	IMG_GB_V5_0062,
	IMG_GB_V5_0063,
	IMG_GB_V5_0064,
	IMG_GB_V5_0065,
	IMG_GB_V5_0066,
	IMG_GB_V5_0067,
	IMG_GB_V5_0068,
	IMG_GB_V5_0069,
	IMG_GB_V5_0070,
	IMG_GB_V5_0071,
	IMG_GB_V5_0072,
	IMG_GB_V5_0073,
	IMG_GB_V5_0074,
	IMG_GB_V5_0075,
	IMG_GB_V5_0076,
	IMG_GB_V5_0077,
	IMG_GB_V5_0078,
	IMG_GB_V5_0079,
	IMG_GB_V5_0080,
	IMG_GB_V5_0081,
	IMG_GB_V5_0082,
	IMG_GB_V5_0083,
	IMG_GB_V5_0084,
	IMG_GB_V5_0085,
	IMG_GB_V5_0086,
	IMG_GB_V5_0087,
	IMG_GB_V5_0088,
	IMG_GB_V5_0089,
	IMG_GB_V5_0090,
	IMG_GB_V5_0091,
	IMG_GB_V5_0092,
	IMG_GB_V5_0093,
	IMG_GB_V5_0094,
	IMG_GB_V5_0095,
	IMG_GB_V5_0096,
	IMG_GB_V5_0097,
	IMG_GB_V5_0098,
	IMG_GB_V5_0099,
	IMG_GB_V5_0100,
	IMG_GB_V5_0101,
	IMG_GB_V5_0102,
	IMG_GB_V5_0103,
	IMG_GB_V5_0104,
	IMG_GB_V5_0105,
	IMG_GB_V5_0106,
	IMG_GB_V5_0107,
	IMG_GB_V5_0108,
	IMG_GB_V5_0109,
	IMG_GB_V5_0110,
	IMG_GB_V5_0111,
	IMG_GB_V5_0112,
	IMG_GB_V5_0113,
	IMG_GB_V5_0114,
	IMG_GB_V5_0115,
	IMG_GB_V5_0116,
	IMG_GB_V5_0117,
	IMG_GB_V5_0118,
	IMG_GB_V5_0119,
	IMG_GB_V5_0120,
	IMG_GB_V5_0121,
	IMG_GB_V5_0122,
	IMG_GB_V5_0123,
	IMG_GB_V5_0124,
	IMG_GB_V5_0125,
	IMG_GB_V5_0126,
	IMG_GB_V5_0127,
	IMG_GB_V5_0128,
	IMG_GB_V5_0129,
	IMG_GB_V5_0130,
	IMG_GB_V5_0131,
	IMG_GB_V5_0132,
	IMG_GB_V5_0133,
	IMG_GB_V5_0134,
	IMG_GB_V5_0135,
	IMG_GB_V5_0136,
	IMG_GB_V5_0137,
	IMG_GB_V5_0138,
	IMG_GB_V5_0139,
	IMG_GB_V5_0140,
	IMG_GB_V5_0141,
	IMG_GB_V5_0142,
	IMG_GB_V5_0143,
	IMG_GB_V5_0144,
	IMG_GB_V5_0145,
	IMG_GB_V5_0146,
	IMG_GB_V5_0147,
	IMG_GB_V5_0148,
	IMG_GB_V5_0149,
	IMG_GB_V5_0150,
	IMG_GB_V5_0151,
	IMG_GB_V5_0152,
	IMG_GB_V5_0153,
	IMG_GB_V5_0154,
	IMG_GB_V5_0155,
	IMG_GB_V5_0156,
	IMG_GB_V5_0157,
	IMG_GB_V5_0158,
	IMG_GB_V5_0159,
	IMG_GB_V5_0160,
	IMG_GB_V5_0161,
	IMG_GB_V5_0162,
	IMG_GB_V5_0163,
	IMG_GB_V5_0164,
	IMG_GB_V5_0165,
	IMG_GB_V5_0166,
	IMG_GB_V5_0167,
	IMG_GB_V5_0168,
	
/* 输入法图片*/
	GB_IME_LOWERCASE_abc_IMG,
    GB_IME_UPPERCASE_ABC_IMG,
    GB_IME_NUMBER_IMG,
    GB_IME_SYMBOLS_IMG,
    
#if defined(__MMI_GBIME_LANG_SM_CHINESE__)
	GB_IME_SMART_PINYIN_IMG,
	GB_IME_SM_STROKE_IMG,
#endif
#if defined(__MMI_GBIME_LANG_TR_CHINESE__)
	GB_IME_TR_STROKE_IMG,
	GB_IME_SMART_BPMF_IMG,
#endif	

#ifdef __MMI_GBIME_LANG_ENGLISH__
       GB_IME_SMART_UPPERCASE_ENGLISH_IMG,
       GB_IME_SMART_LOWERCASE_ENGLISH_IMG,
#endif

#ifdef 	__MMI_GBIME_LANG_FRENCH__
       GB_IME_SMART_UPPERCASE_FRENCH_IMG,
       GB_IME_SMART_LOWERCASE_FRENCH_IMG,
       GB_IME_MULTITAP_UPPERCASE_FRENCH_IMG,
       GB_IME_MULTITAP_LOWERCASE_FRENCH_IMG,
#endif

#ifdef 	__MMI_GBIME_LANG_ARABIC__
	GB_IME_SMART_ARABIC_IMG,
	GB_IME_MULTITAP_ARABIC_IMG,
	GB_IME_MULTITAP_ARABIC_NUM_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_THAI__
	GB_IME_SMART_THAI_IMG,
	GB_IME_MULTITAP_THAI_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_GREEK__
       GB_IME_SMART_UPPERCASE_GREEK_IMG,
       GB_IME_SMART_LOWERCASE_GREEK_IMG,
       GB_IME_MULTITAP_UPPERCASE_GREEK_IMG,
       GB_IME_MULTITAP_LOWERCASE_GREEK_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_TURKISH__
       GB_IME_SMART_UPPERCASE_TURKISH_IMG,
       GB_IME_SMART_LOWERCASE_TURKISH_IMG,
       GB_IME_MULTITAP_UPPERCASE_TURKISH_IMG,
       GB_IME_MULTITAP_LOWERCASE_TURKISH_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_VIETNAMESE__
       GB_IME_SMART_UPPERCASE_VIETNAMESE_IMG,
       GB_IME_SMART_LOWERCASE_VIETNAMESE_IMG,
       GB_IME_MULTITAP_UPPERCASE_VIETNAMESE_IMG,
       GB_IME_MULTITAP_LOWERCASE_VIETNAMESE_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_RUSSIAN__
       GB_IME_SMART_UPPERCASE_RUSSIAN_IMG,
       GB_IME_SMART_LOWERCASE_RUSSIAN_IMG,
       GB_IME_MULTITAP_UPPERCASE_RUSSIAN_IMG,
       GB_IME_MULTITAP_LOWERCASE_RUSSIAN_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_SPANISH__
       GB_IME_SMART_UPPERCASE_SPANISH_IMG,
       GB_IME_SMART_LOWERCASE_SPANISH_IMG,
       GB_IME_MULTITAP_UPPERCASE_SPANISH_IMG,
       GB_IME_MULTITAP_LOWERCASE_SPANISH_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_PORTUGUESE__
       GB_IME_SMART_UPPERCASE_PORTUGUESE_IMG,
       GB_IME_SMART_LOWERCASE_PORTUGUESE_IMG,
       GB_IME_MULTITAP_UPPERCASE_PORTUGUESE_IMG,
       GB_IME_MULTITAP_LOWERCASE_PORTUGUESE_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_GERMAN__
       GB_IME_SMART_UPPERCASE_GERMAN_IMG,
       GB_IME_SMART_LOWERCASE_GERMAN_IMG,
       GB_IME_MULTITAP_UPPERCASE_GERMAN_IMG,
       GB_IME_MULTITAP_LOWERCASE_GERMAN_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_PERSIAN__
	GB_IME_SMART_PERSIAN_IMG,
	GB_IME_MULTITAP_PERSIAN_IMG,
#endif

#ifdef	__MMI_GBIME_LANG_ITALIAN__
       GB_IME_SMART_UPPERCASE_ITALIAN_IMG,
       GB_IME_SMART_LOWERCASE_ITALIAN_IMG,
       GB_IME_MULTITAP_UPPERCASE_ITALIAN_IMG,
       GB_IME_MULTITAP_LOWERCASE_ITALIAN_IMG,
#endif

#ifdef __MMI_GBIME_LANG_HINDI__
	GB_IME_SMART_HINDI_IMG,
	GB_IME_MULTITAP_HINDI_IMG,
#endif

#ifdef __MMI_GBIME_LANG_MALAY__
       GB_IME_SMART_UPPERCASE_MALAY_IMG,
       GB_IME_SMART_LOWERCASE_MALAY_IMG,
       GB_IME_MULTITAP_UPPERCASE_MALAY_IMG,
       GB_IME_MULTITAP_LOWERCASE_MALAY_IMG,
#endif

#ifdef __MMI_GBIME_LANG_BULGARIAN__
       GB_IME_SMART_UPPERCASE_BULGARIAN_IMG,
       GB_IME_SMART_LOWERCASE_BULGARIAN_IMG,
       GB_IME_MULTITAP_UPPERCASE_BULGARIAN_IMG,
       GB_IME_MULTITAP_LOWERCASE_BULGARIAN_IMG,
#endif

#ifdef __MMI_GBIME_LANG_INDONESIAN__
       GB_IME_SMART_UPPERCASE_INDONESIAN_IMG,
       GB_IME_SMART_LOWERCASE_INDONESIAN_IMG,
       GB_IME_MULTITAP_UPPERCASE_INDONESIAN_IMG,
       GB_IME_MULTITAP_LOWERCASE_INDONESIAN_IMG,
#endif

    IMG_VKBD_GUOBI_CAND,    
    IMG_GB_STROKE_5,
    IMG_GB_COMP_XIAO,
    IMG_GB_COMP_ZHU,

    /* add new image ID above this line */
    IMG_ID_GBIME_END
} IMG_ID_GBIME_ENUM;

#endif /* __GBIME__ */ 

#endif /* __GBIMERES_DEF_H__ */ 
